// vue/src/board/WeekGrid.vue
<script setup lang="ts">
import type { EventRow } from "../api";
import EventCard from "./EventCard.vue";
import {
  HOURS,
  type Day,
  dayElementId,
  formatHour,
  parseEventElementId,
  slotElementId,
} from "./calendar";
import { readDrag } from "./dragging";
import type { BoardState } from "./useBoard";

const props = defineProps<{ days: Day[]; board: BoardState }>();

/**
 * Hours down the side, days across, and a container that overflows on both axes —
 * which is what makes the two scrolling interactions real rather than notional.
 */
function at(day: string, hour: number): EventRow | undefined {
  return props.board.scheduled.value.find(
    (event) => event.day === day && event.start_hour === hour,
  );
}

function drop(day: string, hour: number, dropEvent: DragEvent): void {
  dropEvent.preventDefault();
  const eventId = parseEventElementId(readDrag(dropEvent.dataTransfer) ?? "");
  if (eventId !== null) {
    void props.board.schedule(eventId, day, hour);
  }
}
</script>

<template>
  <div class="grid-scroller">
    <div
      class="grid"
      :style="{ gridTemplateColumns: `5rem repeat(${props.days.length}, 14rem)` }"
    >
      <div class="grid-corner" />
      <div
        v-for="day in props.days"
        :key="day.date"
        :id="dayElementId(day.date)"
        class="grid-day-head"
      >
        {{ day.label }}
      </div>
      <template v-for="hour in HOURS" :key="hour">
        <div class="grid-hour">{{ formatHour(hour) }}</div>
        <div
          v-for="day in props.days"
          :key="`${day.date}-${hour}`"
          :id="slotElementId(day.date, hour)"
          class="grid-slot"
          :class="{ 'grid-slot-taken': at(day.date, hour) !== undefined }"
          :aria-label="`${day.label} ${formatHour(hour)}`"
          @dragover.prevent
          @drop="drop(day.date, hour, $event)"
        >
          <EventCard
            v-if="at(day.date, hour) !== undefined"
            :event="at(day.date, hour)!"
            :selected="props.board.selection.value === at(day.date, hour)!.id"
            @select="props.board.select"
          />
        </div>
      </template>
    </div>
  </div>
</template>

// angular/src/app/board/week-grid.component.ts
import { Component, input } from "@angular/core";
import { BoardService } from "./board.service";
import {
  HOURS,
  type Day,
  dayElementId,
  formatHour,
  parseEventElementId,
  slotElementId,
} from "./calendar";
import { readDrag } from "./dragging";
import { EventCardComponent } from "./event-card.component";

/**
 * Hours down the side, days across, and a container that overflows on both axes,
 * which is what makes the two scrolling interactions real rather than notional.
 */
@Component({
  selector: "app-week-grid",
  imports: [EventCardComponent],
  template: `
    <div class="grid-scroller">
      <div class="grid" [style.gridTemplateColumns]="columns()">
        <div class="grid-corner"></div>
        @for (day of days(); track day.date) {
          <div [id]="dayId(day)" class="grid-day-head">{{ day.label }}</div>
        }
        @for (hour of hours; track hour) {
          <div class="grid-hour">{{ label(hour) }}</div>
          @for (day of days(); track day.date) {
            <div
              [id]="slotId(day, hour)"
              class="grid-slot"
              [class.grid-slot-taken]="board.at(day.date, hour) !== undefined"
              [attr.aria-label]="day.label + ' ' + label(hour)"
              (dragover)="$event.preventDefault()"
              (drop)="drop(day.date, hour, $event)"
            >
              @if (board.at(day.date, hour); as event) {
                <app-event-card
                  [event]="event"
                  [selected]="board.selection() === event.id"
                  (select)="board.select($event)"
                />
              }
            </div>
          }
        }
      </div>
    </div>
  `,
  // Angular wraps every component in a host element, which would sit between the
  // page's grid and its children and break the layout. `display: contents` takes
  // the host out of layout so the children participate in the parent grid as they
  // do in the other apps. This is the one thing about the board that is Angular's
  // rather than the board's.
  styles: [":host { display: contents; }"],
})
export class WeekGridComponent {
  readonly days = input.required<Day[]>();
  readonly hours = HOURS;

  constructor(readonly board: BoardService) {}

  columns(): string {
    return `5rem repeat(${this.days().length}, 14rem)`;
  }

  dayId(day: Day): string {
    return dayElementId(day.date);
  }

  slotId(day: Day, hour: number): string {
    return slotElementId(day.date, hour);
  }

  label(hour: number): string {
    return formatHour(hour);
  }

  drop(day: string, hour: number, dropEvent: DragEvent): void {
    dropEvent.preventDefault();
    const eventId = parseEventElementId(readDrag(dropEvent.dataTransfer) ?? "");
    if (eventId !== null) {
      void this.board.schedule(eventId, day, hour);
    }
  }
}
