// svelte/src/board/EventCard.svelte
<script lang="ts">
  import type { EventRow } from "../api";
  import { eventElementId, formatHour } from "./calendar";
  import { beginDrag, endDrag } from "./dragging";

  /**
   * The `id` attribute is what the agent addresses: the same string the page map
   * reports and `resolvePageTarget` resolves.
   */
  let {
    event,
    selected,
    compact = false,
    onselect,
  }: {
    event: EventRow;
    selected: boolean;
    compact?: boolean;
    onselect: (eventId: number) => void;
  } = $props();
</script>

<article
  id={eventElementId(event.id)}
  class="card"
  class:card-selected={selected}
  class:card-compact={compact}
  draggable="true"
  aria-label={event.title}
  ondragstart={(dragEvent) => beginDrag(eventElementId(event.id), dragEvent.dataTransfer)}
  ondragend={endDrag}
  onclick={() => onselect(event.id)}
>
  <span class="card-title">{event.title}</span>
  <span class="card-meta">
    {event.start_hour === null ? "unscheduled" : formatHour(event.start_hour)}{event.room === ""
      ? ""
      : ` · ${event.room}`}
  </span>
</article>

// vue/src/board/EventCard.vue
<script setup lang="ts">
import type { EventRow } from "../api";
import { eventElementId, formatHour } from "./calendar";
import { beginDrag, endDrag } from "./dragging";

const props = defineProps<{
  event: EventRow;
  selected: boolean;
  compact?: boolean;
}>();

const emit = defineEmits<{ select: [eventId: number] }>();

/**
 * The `id` attribute is what the agent addresses: the same string the page map
 * reports and `resolvePageTarget` resolves.
 */
</script>

<template>
  <article
    :id="eventElementId(props.event.id)"
    class="card"
    :class="{ 'card-selected': props.selected, 'card-compact': props.compact }"
    draggable="true"
    :aria-label="props.event.title"
    @dragstart="beginDrag(eventElementId(props.event.id), $event.dataTransfer)"
    @dragend="endDrag()"
    @click="emit('select', props.event.id)"
  >
    <span class="card-title">{{ props.event.title }}</span>
    <span class="card-meta">
      {{ props.event.start_hour === null ? "unscheduled" : formatHour(props.event.start_hour) }}
      {{ props.event.room === "" ? "" : ` · ${props.event.room}` }}
    </span>
  </article>
</template>
