// vue/src/App.vue
<script setup lang="ts">
import type { RouteMap } from "@artooi/ag-ui-web-component";
import { computed } from "vue";
import { useRoute, useRouter } from "vue-router";
import Assistant from "./assistant/Assistant.vue";
import AgendaView from "./board/AgendaView.vue";
import Backlog from "./board/Backlog.vue";
import WeekGrid from "./board/WeekGrid.vue";
import { isoDate, labelForIso, weekDays } from "./board/calendar";
import { buildPageMap, type ViewName } from "./board/pageMap";
import { useBoard } from "./board/useBoard";

/** The routes the agent may navigate to, matching the router below. */
const ROUTE_MAP: RouteMap = [
  {
    id: "week",
    path: "/week",
    title: "Week grid",
    description: "Five days across, hours down the side. Drop targets for scheduling.",
  },
  {
    id: "day",
    path: "/day",
    title: "Day column",
    description: "One day of the grid, for a close look at a single day.",
  },
  {
    id: "agenda",
    path: "/agenda",
    title: "Agenda list",
    description: "Everything scheduled as a flat list, grouped by day. No drop targets.",
  },
];

const board = useBoard();
const route = useRoute();
const router = useRouter();
const days = weekDays();
const today =
  days.find((day) => day.date === isoDate(new Date())) ??
  days[0] ?? { date: isoDate(new Date()), label: labelForIso(isoDate(new Date())) };

const view = computed<ViewName>(() =>
  route.path.startsWith("/agenda") ? "agenda" : route.path.startsWith("/day") ? "day" : "week",
);
const visibleDays = computed(() => (view.value === "day" ? [today] : days));

function snapshot() {
  return {
    saving: board.saving.value,
    filter: board.filter.value,
    selection: board.selection.value,
    scheduled: board.scheduled.value,
    backlog: board.backlog.value,
  };
}
</script>

<template>
  <div class="layout">
    <header class="topbar">
      <h1>Scheduling board</h1>
      <nav>
        <button
          v-for="entry in ROUTE_MAP"
          :key="entry.id"
          type="button"
          :class="{ 'nav-current': view === entry.id }"
          @click="router.push(entry.path)"
        >
          {{ entry.title }}
        </button>
      </nav>
      <label class="filter">
        Room
        <select :value="board.filter.value" @change="board.setFilter(($event.target as HTMLSelectElement).value)">
          <option value="all">all</option>
          <option v-for="room in board.rooms.value" :key="room" :value="room">{{ room }}</option>
        </select>
      </label>
    </header>

    <p v-if="board.error.value !== null" class="error" role="alert">
      {{ board.error.value }}
    </p>

    <main class="main">
      <div class="board">
        <WeekGrid v-if="view === 'week'" :days="days" :board="board" />
        <WeekGrid v-else-if="view === 'day'" :days="[today]" :board="board" />
        <AgendaView v-else :board="board" />
        <Backlog :board="board" />
      </div>

      <Assistant
        :route-map="ROUTE_MAP"
        :navigate="(path: string) => router.push(path)"
        :get-page-map="() => buildPageMap(view, visibleDays, snapshot())"
        :read-board-state="
          () => ({
            view,
            filter: board.filter.value,
            selection: board.selection.value,
            scheduled: board.scheduled.value.length,
            backlog: board.backlog.value.length,
          })
        "
        :write-board-state="
          (patch: Record<string, unknown>) => {
            if (typeof patch['room'] === 'string') {
              board.setFilter(patch['room']);
            }
            if (patch['selection'] === null || typeof patch['selection'] === 'number') {
              board.select(patch['selection'] as number | null);
            }
            return { ok: true };
          }
        "
      />
    </main>
  </div>
</template>

// react/src/App.tsx
import type { RouteMap } from "@artooi/ag-ui-web-component";
import { useMemo } from "react";
import {
  Navigate,
  Route,
  Routes,
  useLocation,
  useNavigate,
} from "react-router-dom";
import { Assistant } from "./assistant/Assistant";
import { AgendaView } from "./board/AgendaView";
import { Backlog } from "./board/Backlog";
import { DayView } from "./board/DayView";
import { WeekGrid } from "./board/WeekGrid";
import { isoDate, labelForIso, weekDays } from "./board/calendar";
import { buildPageMap, type ViewName } from "./board/pageMap";
import { useBoard } from "./board/useBoard";

/**
 * The routes the agent may navigate to. Ids are what it addresses; paths are the
 * app's own. Because `navigate` is wired to the router below, switching views
 * never reloads the page and the run loop simply continues.
 */
const ROUTE_MAP: RouteMap = [
  {
    id: "week",
    path: "/week",
    title: "Week grid",
    description: "Five days across, hours down the side. Drop targets for scheduling.",
  },
  {
    id: "day",
    path: "/day",
    title: "Day column",
    description: "One day of the grid, for a close look at a single day.",
  },
  {
    id: "agenda",
    path: "/agenda",
    title: "Agenda list",
    description: "Everything scheduled as a flat list, grouped by day. No drop targets.",
  },
];

export function App() {
  const board = useBoard();
  const location = useLocation();
  const navigate = useNavigate();
  const days = useMemo(() => weekDays(), []);
  const today = useMemo(() => {
    const iso = isoDate(new Date());
    return days.find((day) => day.date === iso) ?? days[0] ?? { date: iso, label: labelForIso(iso) };
  }, [days]);

  const view: ViewName = location.pathname.startsWith("/agenda")
    ? "agenda"
    : location.pathname.startsWith("/day")
      ? "day"
      : "week";
  const visibleDays = view === "day" ? [today] : days;

  return (
    <div className="layout">
      <header className="topbar">
        <h1>Scheduling board</h1>
        <nav>
          {ROUTE_MAP.map((route) => (
            <button
              key={route.id}
              type="button"
              className={view === route.id ? "nav-current" : undefined}
              onClick={() => navigate(route.path)}
            >
              {route.title}
            </button>
          ))}
        </nav>
        <label className="filter">
          Room
          <select value={board.filter} onChange={(event) => board.setFilter(event.target.value)}>
            <option value="all">all</option>
            {board.rooms.map((room) => (
              <option key={room} value={room}>
                {room}
              </option>
            ))}
          </select>
        </label>
      </header>

      {board.error === null ? null : (
        <p className="error" role="alert">
          {board.error}
        </p>
      )}

      <main className="main">
        <div className="board">
          <Routes>
            <Route path="/" element={<Navigate to="/week" replace />} />
            <Route path="/week" element={<WeekGrid days={days} board={board} />} />
            <Route path="/day" element={<DayView day={today} board={board} />} />
            <Route path="/agenda" element={<AgendaView board={board} />} />
          </Routes>
          <Backlog board={board} />
        </div>

        <Assistant
          routeMap={ROUTE_MAP}
          navigate={(path) => navigate(path)}
          getPageMap={() =>
            buildPageMap(view, visibleDays, {
              saving: board.saving,
              filter: board.filter,
              selection: board.selection,
              scheduled: board.scheduled,
              backlog: board.backlog,
            })
          }
          readBoardState={() => ({
            view,
            filter: board.filter,
            selection: board.selection,
            scheduled: board.scheduled.length,
            backlog: board.backlog.length,
          })}
          writeBoardState={(patch) => {
            if (typeof patch["room"] === "string") {
              board.setFilter(patch["room"]);
            }
            if (patch["selection"] === null || typeof patch["selection"] === "number") {
              board.select(patch["selection"] as number | null);
            }
            return { ok: true };
          }}
        />
      </main>
    </div>
  );
}
