// angular/src/app/app.ts
import { Component, computed, signal } from "@angular/core";
import { Router } from "@angular/router";
import type { RouteMap } from "@artooi/ag-ui-web-component";
import { AssistantComponent } from "./assistant/assistant.component";
import { AgendaComponent } from "./board/agenda.component";
import { BacklogComponent } from "./board/backlog.component";
import { BoardService } from "./board/board.service";
import { isoDate, labelForIso, weekDays } from "./board/calendar";
import { buildPageMap, type ViewName } from "./board/pageMap";
import { WeekGridComponent } from "./board/week-grid.component";

/** The routes the agent may navigate to, matching `app.routes.ts`. */
const ROUTE_MAP: RouteMap = [
  {
    id: "week",
    path: "/week",
    title: "Week grid",
    description: "Five days across, hours down the side. Drop targets for scheduling.",
  },
  {
    id: "day",
    path: "/day",
    title: "Day column",
    description: "One day of the grid, for a close look at a single day.",
  },
  {
    id: "agenda",
    path: "/agenda",
    title: "Agenda list",
    description: "Everything scheduled as a flat list, grouped by day. No drop targets.",
  },
];

@Component({
  selector: "app-root",
  imports: [WeekGridComponent, BacklogComponent, AgendaComponent, AssistantComponent],
  template: `
    <div class="layout">
      <header class="topbar">
        <h1>Scheduling board</h1>
        <nav>
          @for (entry of routeMap; track entry.id) {
            <button
              type="button"
              [class.nav-current]="view() === entry.id"
              (click)="go(entry.path)"
            >
              {{ entry.title }}
            </button>
          }
        </nav>
        <label class="filter">
          Room
          <select [value]="board.filter()" (change)="onFilter($event)">
            <option value="all">all</option>
            @for (room of board.rooms(); track room) {
              <option [value]="room">{{ room }}</option>
            }
          </select>
        </label>
      </header>

      @if (board.error() !== null) {
        <p class="error" role="alert">{{ board.error() }}</p>
      }

      <main class="main">
        <div class="board">
          @if (view() === "agenda") {
            <app-agenda />
          } @else {
            <app-week-grid [days]="visibleDays()" />
          }
          <app-backlog />
        </div>

        <app-assistant
          [routeMap]="routeMap"
          [navigate]="navigate"
          [getPageMap]="pageMap"
          [readBoardState]="readBoardState"
          [writeBoardState]="writeBoardState"
        />
      </main>
    </div>
  `,
})
export class App {
  readonly routeMap = ROUTE_MAP;
  private readonly path = signal(window.location.pathname);

  readonly view = computed<ViewName>(() => {
    const path = this.path();
    return path.startsWith("/agenda") ? "agenda" : path.startsWith("/day") ? "day" : "week";
  });

  private readonly days = weekDays();
  private readonly today =
    this.days.find((day) => day.date === isoDate(new Date())) ??
    this.days[0] ?? { date: isoDate(new Date()), label: labelForIso(isoDate(new Date())) };

  readonly visibleDays = computed(() => (this.view() === "day" ? [this.today] : this.days));

  constructor(
    readonly board: BoardService,
    private readonly router: Router,
  ) {
    void this.board.reload();
    // The URL is the source of truth for the view; the agent changes it through
    // `navigate`, exactly as the buttons do.
    this.router.events.subscribe(() => {
      this.path.set(window.location.pathname);
    });
  }

  /** Passed to the assistant: the single seam that makes this host a single-page app. */
  readonly navigate = (path: string): void => {
    void this.router.navigateByUrl(path);
  };

  readonly pageMap = () => buildPageMap(this.view(), this.visibleDays(), this.board.snapshot());

  readonly readBoardState = () => ({
    view: this.view(),
    filter: this.board.filter(),
    selection: this.board.selection(),
    scheduled: this.board.scheduled().length,
    backlog: this.board.backlog().length,
  });

  readonly writeBoardState = (patch: Record<string, unknown>) => {
    if (typeof patch["room"] === "string") {
      this.board.setFilter(patch["room"]);
    }
    if (patch["selection"] === null || typeof patch["selection"] === "number") {
      this.board.select(patch["selection"] as number | null);
    }
    return { ok: true };
  };

  go(path: string): void {
    this.navigate(path);
  }

  onFilter(changeEvent: Event): void {
    this.board.setFilter((changeEvent.target as HTMLSelectElement).value);
  }
}

// svelte/src/App.svelte
<script lang="ts">
  import type { RouteMap } from "@artooi/ag-ui-web-component";
  import Assistant from "./assistant/Assistant.svelte";
  import AgendaView from "./board/AgendaView.svelte";
  import Backlog from "./board/Backlog.svelte";
  import WeekGrid from "./board/WeekGrid.svelte";
  import { Board } from "./board/board.svelte";
  import { isoDate, labelForIso, weekDays } from "./board/calendar";
  import { buildPageMap, type ViewName } from "./board/pageMap";
  import { router } from "./router.svelte";

  /** The routes the agent may navigate to, matching the router. */
  const ROUTE_MAP: RouteMap = [
    {
      id: "week",
      path: "/week",
      title: "Week grid",
      description: "Five days across, hours down the side. Drop targets for scheduling.",
    },
    {
      id: "day",
      path: "/day",
      title: "Day column",
      description: "One day of the grid, for a close look at a single day.",
    },
    {
      id: "agenda",
      path: "/agenda",
      title: "Agenda list",
      description: "Everything scheduled as a flat list, grouped by day. No drop targets.",
    },
  ];

  const board = new Board();
  void board.reload();

  const days = weekDays();
  const today =
    days.find((day) => day.date === isoDate(new Date())) ??
    days[0] ?? { date: isoDate(new Date()), label: labelForIso(isoDate(new Date())) };

  const view = $derived<ViewName>(
    router.path.startsWith("/agenda") ? "agenda" : router.path.startsWith("/day") ? "day" : "week",
  );
  const visibleDays = $derived(view === "day" ? [today] : days);
</script>

<div class="layout">
  <header class="topbar">
    <h1>Scheduling board</h1>
    <nav>
      {#each ROUTE_MAP as entry (entry.id)}
        <button
          type="button"
          class:nav-current={view === entry.id}
          onclick={() => router.navigate(entry.path)}
        >
          {entry.title}
        </button>
      {/each}
    </nav>
    <label class="filter">
      Room
      <select value={board.filter} onchange={(e) => board.setFilter(e.currentTarget.value)}>
        <option value="all">all</option>
        {#each board.rooms as room (room)}
          <option value={room}>{room}</option>
        {/each}
      </select>
    </label>
  </header>

  {#if board.error !== null}
    <p class="error" role="alert">{board.error}</p>
  {/if}

  <main class="main">
    <div class="board">
      {#if view === "agenda"}
        <AgendaView {board} />
      {:else}
        <WeekGrid days={visibleDays} {board} />
      {/if}
      <Backlog {board} />
    </div>

    <Assistant
      routeMap={ROUTE_MAP}
      navigate={(path) => router.navigate(path)}
      getPageMap={() => buildPageMap(view, visibleDays, board.snapshot())}
      readBoardState={() => ({
        view,
        filter: board.filter,
        selection: board.selection,
        scheduled: board.scheduled.length,
        backlog: board.backlog.length,
      })}
      writeBoardState={(patch) => {
        if (typeof patch["room"] === "string") {
          board.setFilter(patch["room"]);
        }
        if (patch["selection"] === null || typeof patch["selection"] === "number") {
          board.select(patch["selection"] as number | null);
        }
        return { ok: true };
      }}
    />
  </main>
</div>
