// svelte/src/board/EventCard.svelte
<script lang="ts">
  import type { EventRow } from "../api";
  import { eventElementId, formatHour } from "./calendar";
  import { beginDrag, endDrag } from "./dragging";

  /**
   * The `id` attribute is what the agent addresses: the same string the page map
   * reports and `resolvePageTarget` resolves.
   */
  let {
    event,
    selected,
    compact = false,
    onselect,
  }: {
    event: EventRow;
    selected: boolean;
    compact?: boolean;
    onselect: (eventId: number) => void;
  } = $props();
</script>

<article
  id={eventElementId(event.id)}
  class="card"
  class:card-selected={selected}
  class:card-compact={compact}
  draggable="true"
  aria-label={event.title}
  ondragstart={(dragEvent) => beginDrag(eventElementId(event.id), dragEvent.dataTransfer)}
  ondragend={endDrag}
  onclick={() => onselect(event.id)}
>
  <span class="card-title">{event.title}</span>
  <span class="card-meta">
    {event.start_hour === null ? "unscheduled" : formatHour(event.start_hour)}{event.room === ""
      ? ""
      : ` · ${event.room}`}
  </span>
</article>

// react/src/board/EventCard.tsx
import type { EventRow } from "../api";
import { eventElementId, formatHour } from "./calendar";
import { beginDrag, endDrag } from "./dragging";

interface Props {
  event: EventRow;
  selected: boolean;
  onSelect: (eventId: number) => void;
  compact?: boolean;
}

/**
 * One draggable card. The `id` attribute is what the agent addresses: it is the
 * same string `getPageMap` reports and `resolvePageTarget` resolves.
 */
export function EventCard({ event, selected, onSelect, compact = false }: Props) {
  return (
    <article
      id={eventElementId(event.id)}
      className={`card${selected ? " card-selected" : ""}${compact ? " card-compact" : ""}`}
      draggable
      onDragStart={(dragEvent) => beginDrag(eventElementId(event.id), dragEvent.dataTransfer)}
      onDragEnd={endDrag}
      onClick={() => onSelect(event.id)}
      aria-label={event.title}
    >
      <span className="card-title">{event.title}</span>
      <span className="card-meta">
        {event.start_hour === null ? "unscheduled" : formatHour(event.start_hour)}
        {event.room === "" ? "" : ` · ${event.room}`}
      </span>
    </article>
  );
}
