// vue/src/board/WeekGrid.vue
<script setup lang="ts">
import type { EventRow } from "../api";
import EventCard from "./EventCard.vue";
import {
  HOURS,
  type Day,
  dayElementId,
  formatHour,
  parseEventElementId,
  slotElementId,
} from "./calendar";
import { readDrag } from "./dragging";
import type { BoardState } from "./useBoard";

const props = defineProps<{ days: Day[]; board: BoardState }>();

/**
 * Hours down the side, days across, and a container that overflows on both axes —
 * which is what makes the two scrolling interactions real rather than notional.
 */
function at(day: string, hour: number): EventRow | undefined {
  return props.board.scheduled.value.find(
    (event) => event.day === day && event.start_hour === hour,
  );
}

function drop(day: string, hour: number, dropEvent: DragEvent): void {
  dropEvent.preventDefault();
  const eventId = parseEventElementId(readDrag(dropEvent.dataTransfer) ?? "");
  if (eventId !== null) {
    void props.board.schedule(eventId, day, hour);
  }
}
</script>

<template>
  <div class="grid-scroller">
    <div
      class="grid"
      :style="{ gridTemplateColumns: `5rem repeat(${props.days.length}, 14rem)` }"
    >
      <div class="grid-corner" />
      <div
        v-for="day in props.days"
        :key="day.date"
        :id="dayElementId(day.date)"
        class="grid-day-head"
      >
        {{ day.label }}
      </div>
      <template v-for="hour in HOURS" :key="hour">
        <div class="grid-hour">{{ formatHour(hour) }}</div>
        <div
          v-for="day in props.days"
          :key="`${day.date}-${hour}`"
          :id="slotElementId(day.date, hour)"
          class="grid-slot"
          :class="{ 'grid-slot-taken': at(day.date, hour) !== undefined }"
          :aria-label="`${day.label} ${formatHour(hour)}`"
          @dragover.prevent
          @drop="drop(day.date, hour, $event)"
        >
          <EventCard
            v-if="at(day.date, hour) !== undefined"
            :event="at(day.date, hour)!"
            :selected="props.board.selection.value === at(day.date, hour)!.id"
            @select="props.board.select"
          />
        </div>
      </template>
    </div>
  </div>
</template>

// react/src/board/WeekGrid.tsx
import type { EventRow } from "../api";
import type { BoardState } from "./useBoard";
import {
  HOURS,
  type Day,
  dayElementId,
  formatHour,
  slotElementId,
} from "./calendar";
import { EventCard } from "./EventCard";
import { parseEventElementId } from "./calendar";
import { readDrag } from "./dragging";

interface Props {
  days: Day[];
  board: BoardState;
}

/**
 * The grid: hours down the side, days across, and a scroll container that
 * overflows on both axes. That is what makes the two scrolling interactions
 * (`scroll_to` vertically down the hours, horizontally across the days) real
 * rather than notional.
 */
export function WeekGrid({ days, board }: Props) {
  const at = (day: string, hour: number): EventRow | undefined =>
    board.scheduled.find((event) => event.day === day && event.start_hour === hour);

  const drop = (day: string, hour: number) => (dropEvent: React.DragEvent) => {
    dropEvent.preventDefault();
    const eventId = parseEventElementId(readDrag(dropEvent.dataTransfer) ?? "");
    if (eventId !== null) {
      void board.schedule(eventId, day, hour);
    }
  };

  return (
    <div className="grid-scroller" data-testid="grid-scroller">
      <div className="grid" style={{ gridTemplateColumns: `5rem repeat(${days.length}, 14rem)` }}>
        <div className="grid-corner" />
        {days.map((day) => (
          <div key={day.date} id={dayElementId(day.date)} className="grid-day-head">
            {day.label}
          </div>
        ))}
        {HOURS.map((hour) => (
          <div className="grid-row" key={hour} style={{ display: "contents" }}>
            <div className="grid-hour">{formatHour(hour)}</div>
            {days.map((day) => {
              const event = at(day.date, hour);
              return (
                <div
                  key={`${day.date}-${hour}`}
                  id={slotElementId(day.date, hour)}
                  className={`grid-slot${event === undefined ? "" : " grid-slot-taken"}`}
                  onDragOver={(dragEvent) => dragEvent.preventDefault()}
                  onDrop={drop(day.date, hour)}
                  aria-label={`${day.label} ${formatHour(hour)}`}
                >
                  {event === undefined ? null : (
                    <EventCard
                      event={event}
                      selected={board.selection === event.id}
                      onSelect={board.select}
                    />
                  )}
                </div>
              );
            })}
          </div>
        ))}
      </div>
    </div>
  );
}
